baseURL = ""
title = "lakshay garg"
theme = "coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
themesDir = "themes"
publishDir = "public"

[params]
author = "Lakshay Garg"
description = "My personal website"
keywords = "blog,developer,personal"
info = "I'm a DOGE | Bazinga!"
avatarURL = "images/avatar_old.png"
footerContent = "git commit --signoff"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = 2019
commit = "https://github.com/luizdepra/hugo-coder/tree/"
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
enableTwemoji = true
customCSS = [ ]
customSCSS = [ ]
customJS = [ ]

  [params.fathomAnalytics]
  siteID = "ABCDE"
  serverURL = "analytics.example.com"

  [params.plausibleAnalytics]
  domain = "example.com"
  serverURL = "analytics.example.com"

  [params.goatCounter]
  code = "code"

  [params.cloudflare]
  token = "token"

  [[params.social]]
  name = "Github"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/lakgarg/"

  [[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab"
  weight = 2
  url = "https://gitlab.com/lakgarg/"

  [[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter"
  weight = 3
  url = "https://twitter.com/lakshayg18/"

  [[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/lakshay-garg-5a8567154/"

  [[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram"
  weight = 5
  url = "https://instagram.com/lak.garg"
  
  [[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram"
  weight = 6
  url = "https://t.me/planckton"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[languages.en]
languageName = "English"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Donate"
weight = 4
url = "donate/"

[[languages.en.menu.main]]
name = "Downloads"
weight = 5
url = "http://dl.lakshay.wtf/"