baseURL = ""
title = "lakshaygarg"
theme = "coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
disqusShortname = "yourdiscussshortname"
themesDir = "themes"
publishDir = "public"

[params]
author = "Lakshay Garg"
description = "My personal website"
keywords = "blog,developer,personal"
info = "AOSP Enthusiast | Rockets Lover"
avatarURL = "images/avatar.jpg"
footerContent = "Enter a text here."
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = 2_019
commit = "https://github.com/luizdepra/hugo-coder/tree/"
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
enableTwemoji = true
customCSS = [ ]
customSCSS = [ ]
customJS = [ ]

  [params.fathomAnalytics]
  siteID = "ABCDE"
  serverURL = "analytics.example.com"

  [params.plausibleAnalytics]
  domain = "example.com"
  serverURL = "analytics.example.com"

  [params.goatCounter]
  code = "code"

  [params.cloudflare]
  token = "token"

  [[params.social]]
  name = "Github"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/lakgarg/"

  [[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab"
  weight = 2
  url = "https://gitlab.com/lakgarg/"

  [[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter"
  weight = 3
  url = "https://twitter.com/lakshayg18/"

  [[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/lakshay-garg-5a8567154/"

  [[params.social]]
  name = "Medium"
  icon = "fa fa-medium"
  weight = 5
  url = "https://medium.com/@lakgarg"

  [[params.social]]
  name = "RSS"
  icon = "fa fa-rss"
  weight = 6
  url = "https://myhugosite.com/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[languages.en]
languageName = "English"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"